spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50  # 기존 10 -> 50~100으로 증가 (DB 서버 사양에 따라 조절)
      minimum-idle: 20       # 최소 유휴 연결 수
      connection-timeout: 30000 # 연결을 못 얻으면 30초 후 에러

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

  opensearch:
    uris: ${ELK_URI}
    username: ${OPEN_SEARCH_USERNAME}
    password: ${OPEN_SEARCH_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8080
  forward-headers-strategy: framework


jwt:
  secret-key: ${JWT_SECRET}
  issuer: ${JWT_ISSUER:zeebra-auth}
  clockSkewSec: ${JWT_CLOCK_SKEW_SEC}

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http.converter: DEBUG

springdoc:
  packages-to-scan: com.zeebra

spring.jpa:
  hibernate.ddl-auto: update
  open-in-view: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 50
      generate_statistics: false
      flushMode: COMMIT
      default_batch_fetch_size: 100
      jdbc:
        batch_size: 50
      order_inserts: true
      order_updates: true
  show-sql: false

toss:
  payments:
    secret-key: ${TOSS_PAYMENT_SECRET_KEY}

vapid:
  public.key: BN6WSz7suZPHtrPslZQLuwGf1ZG80OXvnInn1iJ-MLL3HQ_rrUPe0v8Wmo6zaqMaZI_qtrPKqQRjQopPcPORQkU
  private.key: t4LDNFeIXhuonUykBoJMSJBhKBGIe873T340l51FFIY
  subject: mailto:bbyubbu@naver.com

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  security:
    enabled: false
  metrics:
    enable:
      http: true
      jvm: true
      process: true
      system: true
      executor: true
      hikaricp: true
      tomcat: true

chat:
  stomp:
    relay-host: ${RABBITMQ_HOSTNAME}
    relay-port: ${RELAY_PORT}   # STOMP 포트
    system-username: ${STOMP_SYSTEM_USERNAME}
    system-password: ${STOMP_SYSTEM_PASSWORD}
    client-username: ${STOMP_CLIENT_USERNAME}
    client-password: ${STOMP_CLIENT_PASSWORD}